#!/bin/sh

SRC_DIR="src"
SRC_FILE="sources"
WGET="wget -q --show-progress -c -P $SRC_DIR"

[ "$0" != "./scripts/part-0/download" ] && exit 1
[ ! -d "$SRC_DIR" ] && exit 1

while read line; do
  NAME=$(echo "$line" | awk '{print $1}')
  VERSION=$(echo "$line" | awk '{print $2}')
  URL=$(echo "$line" | awk '{print $3}')
  
  if [ ! -z "$URL" ]; then
    DOWN_URL=$(sed "s/*/$VERSION/" <<< "$URL")

    if [ ! -z "$1" ]; then
      if [ "$1" = "$NAME" ]; then
        $WGET "$DOWN_URL"
        exit 0
      else
        continue
      fi
    else
      $WGET "$DOWN_URL"
    fi
  fi
done < "$SRC_FILE"

